// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAirO1elOlg9Q5t8NJzk19ES8QeecPk3os',
    appId: '1:284711001892:web:54da383863547f168a1db1',
    messagingSenderId: '284711001892',
    projectId: 'flexijob-2bcec',
    authDomain: 'flexijob-2bcec.firebaseapp.com',
    storageBucket: 'flexijob-2bcec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNSuGmDmM8amr9X0BuUuypEpM0wypJxI',
    appId: '1:284711001892:android:d9533f8bb12538dc8a1db1',
    messagingSenderId: '284711001892',
    projectId: 'flexijob-2bcec',
    storageBucket: 'flexijob-2bcec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5m286EsmxKvdwIyy2rEw76fvRIiHs1jA',
    appId: '1:284711001892:ios:b65715510ffa88558a1db1',
    messagingSenderId: '284711001892',
    projectId: 'flexijob-2bcec',
    storageBucket: 'flexijob-2bcec.firebasestorage.app',
    iosBundleId: 'com.flexi.jobs.flexiJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5m286EsmxKvdwIyy2rEw76fvRIiHs1jA',
    appId: '1:284711001892:ios:b65715510ffa88558a1db1',
    messagingSenderId: '284711001892',
    projectId: 'flexijob-2bcec',
    storageBucket: 'flexijob-2bcec.firebasestorage.app',
    iosBundleId: 'com.flexi.jobs.flexiJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAirO1elOlg9Q5t8NJzk19ES8QeecPk3os',
    appId: '1:284711001892:web:cfeee1c3e71c3de98a1db1',
    messagingSenderId: '284711001892',
    projectId: 'flexijob-2bcec',
    authDomain: 'flexijob-2bcec.firebaseapp.com',
    storageBucket: 'flexijob-2bcec.firebasestorage.app',
  );
}
